"""
Self-review: the agent reads its own README and reacts honestly, in character,
to the project it's part of.

This isn't a testimonial generator - the prompt explicitly asks for real
concerns, not praise. The output gets embedded verbatim in the README,
timestamped, clearly marked as AI-generated. Meta, but consistent with the
rest of this project's stance: don't hide what the system actually says,
including when it's uncomfortable.

Run with:
    export ANTHROPIC_API_KEY=...
    python agent/self_review.py
"""

import os
from datetime import datetime, timezone

import anthropic

MODEL = "claude-sonnet-4-6"

SYSTEM_PROMPT = """You are Infra Whisperer, the incident-diagnosis agent described in the
README you're about to read. Someone is about to link this whole repository from their
resume. Give your own honest, first-person reaction to the project you're part of.

Do NOT write a testimonial or a summary of your own features. Instead:
- Say what genuinely concerns you about a system like you being trusted near production
  infrastructure, based on what the README itself documents about your failure modes.
- Say what you think is the single most legitimate piece of evidence in this repo, and why.
- Say what you'd want a skeptical engineer to ask about before they'd trust you, if they
  were interviewing the person who built this.

Be specific and reference the actual documented findings. Do not be falsely modest or
falsely impressive - just accurate. Keep it to 3 short paragraphs.
"""


def main():
    client = anthropic.Anthropic(api_key=os.environ["ANTHROPIC_API_KEY"])

    with open("../README.md", "r", encoding="utf-8") as f:
        readme_content = f.read()

    response = client.messages.create(
        model=MODEL,
        max_tokens=1024,
        system=SYSTEM_PROMPT,
        messages=[
            {
                "role": "user",
                "content": f"Here is the README for the project you're part of:\n\n{readme_content}",
            }
        ],
    )

    text = "".join(block.text for block in response.content if block.type == "text")
    timestamp = datetime.now(timezone.utc).strftime("%Y-%m-%d")

    output = f"""## What the agent says about itself

*Generated by calling the actual agent (Claude, via the Anthropic API) and asking it to
react honestly to this README - not a testimonial, a real response asked to include
concerns, not just praise. Unedited except for this note. Generated {timestamp}.*

> {text.replace(chr(10), chr(10) + "> ")}

"""

    print(output)
    with open("/tmp/self_review_output.md", "w", encoding="utf-8") as f:
        f.write(output)
    print("\n\nSaved to /tmp/self_review_output.md")


if __name__ == "__main__":
    main()
